### PR TITLE
Fixed #21 by introducing a configuration parameter to enable the Twig extension

### LINKED ISSUE #21: Login Twig extension requires Session
Hi @bitgandtter ,

I am trying to get my Symfony2 application not to start a session where it isn't needed, but I have a blocker : as soon as this GoogleBundle is loaded in my AppKernel, if I load Twig to render a page, the Twig extensions of this bundle are loaded (because of the "twig.extension" tag), and as one of them requires service "bit_google.client" which itself requires a Symfony2 Session, a session is started.

I see a few ways to handle this situation, and I can implement the solution you will choose among:
* Very easy but not very convenient for your bundle's user: not declaring the Twig extensions services and adding to the bundle's documentation how to enable them
* A bit better: add a boolean configuration parameter (to false by default) to your bundle to enable the Twig extensions, and enable them with a Compiler Pass depending on the value of the configuration parameter
* Change the way the Session is injected to the GoogleClient service to avoid an automatic instantiation, but I'm not really sure how to do this

Please tell me what's your favorite approach (or if you'd use a different one) and I can implement it for you this weekend, as this is a blocker to me in a professional project.

Thanks

### PR DESCRIPTION
**Pull request by David-Guillot**

### CODE REVIEW

**Comment by David-Guillot** [comment]
Actually please don't merge this yet, it doesn't seem to be preventing the creation of a Session... I'll let you know.

**Comment by David-Guillot** [comment]
Hi @bitgandtter 

I see you just merged this PR, can you please create a tag/release for it? Otherwise I'll have to officially maintain my fork of your repository...

Thanks :)

**Comment by bitgandtter** [comment]
https://github.com/bitgandtter/GoogleBundle/tree/1.1

**Comment by David-Guillot** [comment]
Great thank you :)

**Comment by bitgandtter** [comment]
you welcome, is nice to see collaboration around +1

**Pull request merged**
